CREATE VIEW NYPD_COLL_KM AS 
  SELECT LATITUDE, LONGITUDE, DATE, TIME, BOROUGH, ON_STREET_NAME, CROSS_STREET_NAME,
         PERSONS_INJURED, PERSONS_KILLED, CONTRIBUTING_FACTOR_1, VEHICLE_TYPE_CODE_1, CLUSTER_ID
  FROM NYPD_COLL N, NYPD_KM_OUT K
  WHERE N.UNIQUE_KEY = K.ID;